version: '3.4'

services:
  filesharingappcode:
    image: filesharingappcode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5500:5500
